apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-redis
  namespace: monitoring
  labels:
    app: prometheus-redis
data:
  prometheus.yml: >
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    scrape_configs:

      - job_name: 'redis-monitor'
        kubernetes_sd_configs:
        - role: pod
  
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_exporter, __meta_kubernetes_namespace]
          action: keep
          regex: redis;monitoring
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          target_label: 9121

