apiVersion: v1
kind: Service
metadata:
  labels:
    chart: consul-3.7.1
    component: consul-consul
    heritage: Tiller
    release: consul
  name: consul-ui
  namespace: consul
spec:
  ports:
  - name: http
    nodePort: 32744
    port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    component: consul-consul
  sessionAffinity: None
  type: NodePort
