kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: kafka
spec:
  storageClassName: managed-nfs-storage #---需要与上面创建的storageclass的名称一致
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi

