apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-alertmanager
  namespace: monitoring 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "alertmanager"
  resources:
    requests:
      storage: 5Gi

