apiVersion: v1
kind: Service
metadata:
  name: alertmanager 
  namespace: monitoring 
  labels:
    app: alertmanager
spec:
  ports:
  - port: 9093
    name: http
  type: NodePort
  selector:
    app: alertmanager
