global:
  resolve_timeout: 5m
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5m
  receiver: webhook
receivers:
- name: 'webhook'
  webhook_configs:
#  - url: 'http://webhook-dingtalk.monitoring.svc.cluster.local:8060/dingtalk/default-webhook-dingtalk/send'
  - url: 'http://dingtalk.monitoring.svc.cluster.local:8060/dingtalk/webhook/send'
    send_resolved: true
