apiVersion: v1
kind: Service
metadata:
  name: prometheus-saf
  namespace: monitoring
  labels:
    app: prometheus-saf
spec:
  ports:
  - port: 9090
    name: prom-graph
  type: NodePort
  selector:
    app: prometheus-saf
