apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-saf
  namespace: monitoring
  labels:
    app: prometheus-saf
data:
  prometheus.yml: >
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    scrape_configs:

      - job_name: 'saf-monitor'
        kubernetes_sd_configs:
        - role: pod
  
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_ns, __meta_kubernetes_pod_label_framework]
          action: keep
          regex: inc;inc;saf
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep          
          regex: 9145
        - source_labels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          target_label: pod
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: app
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: appId
          replacement: $1
          action: replace 

      - job_name: actuator_adapter_k8s
        metrics_path: '/metrics'
        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_ns, __meta_kubernetes_pod_label_framework]
          action: keep
          regex: inc;inc;saf
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 9147
        - source_labels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          target_label: pod
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: app
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: appId
          replacement: $1
          action: replace

      - job_name: 'actuator'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
        - role: pod
        
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_ns, __meta_kubernetes_pod_label_framework]
          action: keep
          regex: inc;inc;saf
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep          
          regex: 8080
        - source_labels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          target_label: pod
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: app
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: appId
          replacement: $1
          action: replace
