apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-traefik
  namespace: monitoring
  labels:
    app: prometheus-traefik
data:
  prometheus.yml: >
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          #定义报警地址
          - alertmanager:9093

    rule_files:
      #- "traefik-alert-rule.yaml"

    scrape_configs:

      - job_name: 'traefik-monitor'
        kubernetes_sd_configs:
        - role: pod
  
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_appType, __meta_kubernetes_namespace]
          action: keep
          regex: traefik;traefik
