apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: prometheus-k8s
        resources:
          requests:
            storage: 5Gi
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    node.type: monitoring
    #kubernetes.io/os: linux
  podMonitorSelector: {}
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 600Mi
    requests:
      cpu: 400m
      memory: 400Mi
   #requests:
      #memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.11.0
