apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c3-broker-0-log
  namespace: coohua
  labels:
    app: rocketmq-c3-broker-log
    wayne-app: rocketmq-c3-broker-log
    wayne-ns: coohua
spec:
  capacity:
      storage: 20Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c3-broker-log"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /rocketmq-c3-broker-0-log

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c3-broker-0-store
  namespace: coohua
  labels:
    app: rocketmq-c3-broker-store
    wayne-app: rocketmq-c3-broker-store
    wayne-ns: coohua
spec:
  capacity:
      storage: 20Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c3-broker-store"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /rocketmq-c3-broker-0-store

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c3-broker-1-log
  namespace: coohua
  labels:
    app: rocketmq-c3-broker-log
    wayne-app: rocketmq-c3-broker-log
    wayne-ns: coohua
spec:
  capacity:
      storage: 20Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c3-broker-log"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /rocketmq-c3-broker-1-log

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c3-broker-1-store
  namespace: coohua
  labels:
    app: rocketmq-c3-broker-store
    wayne-app: rocketmq-c3-broker-store
    wayne-ns: coohua
spec:
  capacity:
      storage: 20Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c3-broker-store"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 
    path: /rocketmq-c3-broker-1-store
