apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rocketmq-c3-broker-prod-dledger-a
  labels:
    wayne-app: rocketmq-c3-broker-prod
    wayne-ns: coohua
    app: rocketmq-c3-broker-prod-dledger-a
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: rocketmq-c3-broker-prod-dledger-a
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                  - cn-beijing-c
  selector:
    matchLabels:
      app: rocketmq-c3-broker-prod-dledger-a
  template:
    metadata:
      labels:
        wayne-app: rocketmq-c3-broker-prod
        wayne-ns: coohua
        app: rocketmq-c3-broker-prod-dledger-a
    spec:
      containers:
        - name: rocketmq-c3-broker-prod-dledger-a
          image: '/coohua_img/rocketmq:4.5.2'
          command:
            - sh
            - mqbroker
            - '-n'
            - 'rocketmq-c3-namesrv-prod-server:9876'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10909
            - containerPort: 10911
          volumeMounts:
            - mountPath: /data/rocketmq
              name: rocketmq-c3-broker-prod-dledger-a
          resources:
            limits:
              cpu: '4'
              memory: 10Gi
            requests:
              memory: 10Gi
              cpu: '4'
      imagePullSecrets:
        - name: coohua
  volumeClaimTemplates:
    - metadata:
        name: rocketmq-c3-broker-prod-dledger-a
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rocketmq-c3-broker-prod-dledger-a
        resources:
          requests:
            storage: 200Gi
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
