apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apollo-adminservice
  namespace: inc
  labels:
    inc-app: apollo-adminservice
spec:
  replicas: 2
  selector:
    matchLabels:
      inc-app: apollo-adminservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        inc-app: apollo-adminservice
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    inc-app: apollo-adminservice
      volumes:
        - name: apollo-adminservice
          configMap:
            name: apollo-adminservice
            items:
              - key: application-github.properties
                path: application-github.properties
      initContainers:
        - image: 'hpy253215039/alpine-bash:v3.8'
          name: check-apollo-configservice
          command:
            - bash
            - '-c'
            - >-
              curl --connect-timeout 2 --max-time 5 --retry 60 --retry-delay 1
              --retry-max-time 120 apollo-configservice
      containers:
        - name: apollo-adminservice
          image: >-
            hpy253215039/apollo-admin-server:v1.4.0
          securityContext:
            privileged: false
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8090
          volumeMounts:
            - name: apollo-adminservice
              mountPath: /apollo-admin-server/config/application-github.properties
              subPath: application-github.properties
          readinessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
          resources:
            limits:
              memory: 2Gi
              cpu: '1'
            requests:
              cpu: '0.1'
              memory: 1Gi
          env:
            - name: APOLLO_ADMIN_SERVICE_NAME
              value: apollo-adminservice
          envFrom:
            - configMapRef:
                name: apollo-adminservice
      imagePullSecrets:
        - name: inc
