---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-redis-min-master-0
  namespace: redis-cluster-min
spec:
  storageClassName: "redis-cluster-min-master"
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-redis-min-master-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-redis-min-slave-0
  namespace: redis-cluster-min
spec:
  storageClassName: "redis-cluster-min-slave"
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-redis-min-slave-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-redis-min-master-1
  namespace: redis-cluster-min
spec:
  storageClassName: "redis-cluster-min-master"
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-redis-min-master-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-redis-min-slave-1
  namespace: redis-cluster-min
spec:
  storageClassName: "redis-cluster-min-slave"
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-redis-min-slave-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future
