---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    release: redis-cluster-min
  name: redis-cluster-min-headless
  namespace: redis-cluster-min
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis-cluster-min
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    release: redis-cluster-min
  name: redis-cluster-min-master
  namespace: redis-cluster-min
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis-cluster-min
    role: master
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    release: redis-cluster-min
  name: redis-cluster-min-slave
  namespace: redis-cluster-min
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis-cluster-min
    role: slave
  sessionAffinity: None
  type: ClusterIP
