---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-ha
  name: redis-ha-min
  namespace: redis-ha-min
spec:
  clusterIP: None
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  selector:
    app: redis-ha
    release: redis-ha-min
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: redis-ha
  name: redis-ha-min-announce-0
  namespace: redis-ha-min
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  publishNotReadyAddresses: true
  selector:
    app: redis-ha
    release: redis-ha-min
    statefulset.kubernetes.io/pod-name: redis-ha-min-server-0
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: redis-ha
  name: redis-ha-min-announce-1
  namespace: redis-ha-min
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  publishNotReadyAddresses: true
  selector:
    app: redis-ha
    release: redis-ha-min
    statefulset.kubernetes.io/pod-name: redis-ha-min-server-1
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: redis-ha
  name: redis-ha-min-announce-2
  namespace: redis-ha-min
spec:
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  publishNotReadyAddresses: true
  selector:
    app: redis-ha
    release: redis-ha-min
    statefulset.kubernetes.io/pod-name: redis-ha-min-server-2
  sessionAffinity: None
  type: ClusterIP

