---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-ha-min-0
  namespace: redis-ha-min
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-ha-min-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-ha-min-1
  namespace: redis-ha-min
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-ha-min-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-redis-ha-min-2
  namespace: redis-ha-min
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/data-redis-ha-min-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future

