apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-broker-pv0
  namespace: inc
  labels:
    app: rocketmq-c4-broker-prod-server
    wayne-app: rocketmq-c4-broker-prod-server
    wayne-ns: inc
spec:
  capacity:
      storage: 200Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c4-broker-prod-server"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-broker-pv0
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-broker-pv0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-broker-pv1
  namespace: inc
  labels:
    app: rocketmq-c4-broker-prod-server
    wayne-app: rocketmq-c4-broker-prod-server
    wayne-ns: inc
spec:
  capacity:
      storage: 200Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c4-broker-prod-server"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-broker-pv1
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-broker-pv1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-broker-pv2
  namespace: inc
  labels:
    app: rocketmq-c4-broker-prod-server
    wayne-app: rocketmq-c4-broker-prod-server
    wayne-ns: inc
spec:
  capacity:
      storage: 200Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c4-broker-prod-server"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-broker-pv2
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-broker-pv2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketmq-c4-broker-pv3
  namespace: inc
  labels:
    app: rocketmq-c4-broker-prod-server
    wayne-app: rocketmq-c4-broker-prod-server
    wayne-ns: inc
spec:
  capacity:
      storage: 200Gi
  mountOptions:
      - vers=4.0
      - noresvport
  accessModes:
      - ReadWriteOnce
  storageClassName: "rocketmq-c4-broker-prod-server"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/rocketmq-c4-broker-pv3
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /rocketmq-c4-broker-pv3
