kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: kibana
    namespace: es-min-kibana
  spec:
    ports:
    - name: http
      port: 5601
      targetPort: 5601 
    selector:
      app: kibana      
    type: ClusterIP

