apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: apollo-configservice
  namespace: inc
  labels:
    inc-app: apollo-configservice
spec:
  serviceName: apollo-configservice
  #pro:
  #replicas: 3
  replicas: 2
  selector:
    matchLabels:
      inc-app: apollo-configservice
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        inc-app: apollo-configservice
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    inc-app: apollo-configservice
      volumes:
        - name: apollo-configservice
          configMap:
            name: apollo-configservice
            items:
              - key: application-github.properties
                path: application-github.properties
      containers:
        - name: apollo-configservice
          image: >-
            hpy253215039/apollo-config-server:v1.4.0
          securityContext:
            privileged: false
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: apollo-configservice
              mountPath: /apollo-config-server/config/application-github.properties
              subPath: application-github.properties
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
          env:
            - name: APOLLO_CONFIG_SERVICE_NAME
              value: apollo-configservice
          envFrom:
            - configMapRef:
                name: apollo-configservice
          resources:
            limits:
              memory: 2Gi
              cpu: '1'
            requests:
              cpu: '0.1'
              memory: 1Gi
      imagePullSecrets:
        - name: inc
