---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: es-c0-kibana-prod
  namespace: elasticsearch
  labels:
    wayne-app: es-c0
    wayne-ns: elasticsearch
    app: es-c0-kibana-prod
  #生产级配置，用于挂载云厂商的SLB
  #annotations:
  #  kubernetes.io/ingress.class: inc
spec:
  tls: []
  rules:
    - host: kibana.yunding.com
      http:
        paths:
          - backend:
              serviceName: es-c0-kibana-prod
              servicePort: 5601
            path: /
