---
apiVersion: v1
kind: Service
metadata:
  name: es-c0-ingest-headless-prod
  namespace: elasticsearch
  labels:
    wayne-app: es-c0
    wayne-ns: elasticsearch
    app: es-c0-ingest-headless-prod
spec:
  selector:
    app: es-c0-ingest-prod
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: es-c0-ingest-prod
  namespace: elasticsearch
  labels:
    wayne-app: es-c0
    wayne-ns: elasticsearch
    app: es-c0-ingest-prod
spec:
  selector:
    app: es-c0-ingest-prod
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  type: ClusterIP
  sessionAffinity: None
