---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-c0-data0
  namespace: elasticsearch
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "es-c0-data"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.241.1.51
    path: /home/opt/k8s-data/es-c0-data0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-c0-data1
  namespace: elasticsearch
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "es-c0-data"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.241.1.51
    path: /home/opt/k8s-data/es-c0-data1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-c0-data2
  namespace: elasticsearch
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "es-c0-data"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.241.1.51
    path: /home/opt/k8s-data/es-c0-data2

