---
apiVersion: v1
kind: Service
metadata:
  namespace: redis-cluster-min
  name: redis-hkc
  labels:
    app: redis-hkc
spec:
  ports:
  - port: 9720
    targetPort: 9720
    name: client
  - port: 19720
    targetPort: 19720
    name: gossip
  clusterIP: None #创建Headless service
  selector:
    app: redis-hkc
