---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-deployment-1
  namespace: kafka-min
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-service-1
  template:
    metadata:
      labels:
        name: kafka-service-1
        app: kafka-service-1
    spec:
      containers:
      - name: kafka-1
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          #value: [kafka-service1的clusterIP]
          value: 10.102.177.233
        - name: KAFKA_ZOOKEEPER_CONNECT
          #value: zoo1:2181,zoo2:2181,zoo3:2181
          value: zk-hs.zookeeper-min:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        #- name: KAFKA_CREATE_TOPICS
        #  value: mytopic:2:1
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-deployment-2
  namespace: kafka-min
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-service-2
  template:
    metadata:
      labels:
        name: kafka-service-2
        app: kafka-service-2
    spec:
      containers:
      - name: kafka-2
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          #value: [kafka-service2的clusterIP]
          value: 10.96.61.0
        - name: KAFKA_ZOOKEEPER_CONNECT
          #value: zoo1:2181,zoo2:2181,zoo3:2181
          value: zk-hs.zookeeper-min:2181
        - name: KAFKA_BROKER_ID
          value: "2"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-deployment-3
  namespace: kafka-min
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-service-3
  template:
    metadata:
      labels:
        name: kafka-service-3
        app: kafka-service-3
    spec:
      containers:
      - name: kafka-3
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          #value: [kafka-service3的clusterIP]
          value: 10.105.224.222
        - name: KAFKA_ZOOKEEPER_CONNECT
          #value: zoo1:2181,zoo2:2181,zoo3:2181
          value: zk-hs.zookeeper-min:2181
        - name: KAFKA_BROKER_ID
          value: "3"
